stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.8
  before_script:
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pytest

deploy:
  stage: deploy
  image: python:3.8
  only:
    - main
  script:
    - echo "Deploying to Render"
    # No need for Heroku commands here
  environment:
    name: production
    url: https://flasktest1.onrender.com